// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_chat_room.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_join_5fchat_5froom_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_join_5fchat_5froom_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_join_5fchat_5froom_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_join_5fchat_5froom_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_join_5fchat_5froom_2eproto;
class JoinChatRoom;
struct JoinChatRoomDefaultTypeInternal;
extern JoinChatRoomDefaultTypeInternal _JoinChatRoom_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::JoinChatRoom* Arena::CreateMaybeMessage<::JoinChatRoom>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class JoinChatRoom final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JoinChatRoom) */ {
 public:
  inline JoinChatRoom() : JoinChatRoom(nullptr) {}
  ~JoinChatRoom() override;
  explicit constexpr JoinChatRoom(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JoinChatRoom(const JoinChatRoom& from);
  JoinChatRoom(JoinChatRoom&& from) noexcept
    : JoinChatRoom() {
    *this = ::std::move(from);
  }

  inline JoinChatRoom& operator=(const JoinChatRoom& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoinChatRoom& operator=(JoinChatRoom&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JoinChatRoom& default_instance() {
    return *internal_default_instance();
  }
  static inline const JoinChatRoom* internal_default_instance() {
    return reinterpret_cast<const JoinChatRoom*>(
               &_JoinChatRoom_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JoinChatRoom& a, JoinChatRoom& b) {
    a.Swap(&b);
  }
  inline void Swap(JoinChatRoom* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JoinChatRoom* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JoinChatRoom* New() const final {
    return new JoinChatRoom();
  }

  JoinChatRoom* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JoinChatRoom>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JoinChatRoom& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const JoinChatRoom& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoinChatRoom* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JoinChatRoom";
  }
  protected:
  explicit JoinChatRoom(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 2,
    kChatRoomIdFieldNumber = 3,
    kNtTypeFieldNumber = 1,
  };
  // int64 user_id = 2;
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::int64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 chat_room_id = 3;
  void clear_chat_room_id();
  ::PROTOBUF_NAMESPACE_ID::int64 chat_room_id() const;
  void set_chat_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_chat_room_id() const;
  void _internal_set_chat_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 nt_type = 1;
  void clear_nt_type();
  ::PROTOBUF_NAMESPACE_ID::int32 nt_type() const;
  void set_nt_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_nt_type() const;
  void _internal_set_nt_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:JoinChatRoom)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 chat_room_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 nt_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_join_5fchat_5froom_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JoinChatRoom

// int32 nt_type = 1;
inline void JoinChatRoom::clear_nt_type() {
  nt_type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JoinChatRoom::_internal_nt_type() const {
  return nt_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 JoinChatRoom::nt_type() const {
  // @@protoc_insertion_point(field_get:JoinChatRoom.nt_type)
  return _internal_nt_type();
}
inline void JoinChatRoom::_internal_set_nt_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  nt_type_ = value;
}
inline void JoinChatRoom::set_nt_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_nt_type(value);
  // @@protoc_insertion_point(field_set:JoinChatRoom.nt_type)
}

// int64 user_id = 2;
inline void JoinChatRoom::clear_user_id() {
  user_id_ = int64_t{0};
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinChatRoom::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinChatRoom::user_id() const {
  // @@protoc_insertion_point(field_get:JoinChatRoom.user_id)
  return _internal_user_id();
}
inline void JoinChatRoom::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  user_id_ = value;
}
inline void JoinChatRoom::set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:JoinChatRoom.user_id)
}

// int64 chat_room_id = 3;
inline void JoinChatRoom::clear_chat_room_id() {
  chat_room_id_ = int64_t{0};
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinChatRoom::_internal_chat_room_id() const {
  return chat_room_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 JoinChatRoom::chat_room_id() const {
  // @@protoc_insertion_point(field_get:JoinChatRoom.chat_room_id)
  return _internal_chat_room_id();
}
inline void JoinChatRoom::_internal_set_chat_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  chat_room_id_ = value;
}
inline void JoinChatRoom::set_chat_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_chat_room_id(value);
  // @@protoc_insertion_point(field_set:JoinChatRoom.chat_room_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_join_5fchat_5froom_2eproto
